replicaCount: 5
image:
  name: ashwinkmgowda/nodejs-image-demo
  pullPolicy: IfNotPresent
  tag: "staging-70"
# Chose only one type
rolloutStrategy:
  blueGreen:
    autoPromotionEnabled: true
    autoPromotionSeconds: 15
    # canary:
    #   steps:
    #   - setWeight: 20
    #   - pause:
    #       duration: 10s
    #   - setWeight: 40
    #   - pause:
    #       duration: 10s
    #   - setWeight: 60
    #   - pause:
    #       duration: 10s
    #   - setWeight: 80
    #   - pause:
    #       duration: 10s
    #   - setWeight: 100
connection: true
domain: ashwingowda.com
liveDNSName: staging-demo-live.ashwingowda.com
previewDNSName: staging-demo-preview.ashwingowda.com
