replicaCount: 5
image:
  name: ashwinkmgowda/nodejs-image-demo
  pullPolicy: IfNotPresent
<<<<<<< Updated upstream
  tag: "production-71"
=======
  tag: "production-75"
>>>>>>> Stashed changes
# Chose only one type
rolloutStrategy:
  blueGreen:
    autoPromotionEnabled: true
    autoPromotionSeconds: 15

  # canary:
  #   steps:
  #   - setWeight: 20
  #   - pause:
  #       duration: 10s
  #   - setWeight: 40
  #   - pause:
  #       duration: 10s
  #   - setWeight: 60
  #   - pause:
  #       duration: 10s
  #   - setWeight: 80
  #   - pause:
  #       duration: 10s
  #   - setWeight: 100

externalConnection:
  enabled: true
  issuer:
<<<<<<< Updated upstream
    # selfSigned: {}
    LetsEncryptStaging:
      email: kmashwinrocks@gmail.com
=======
    selfSigned: {}
    # LetsEncryptStaging:
    #   email: kmashwinrocks@gmail.com
>>>>>>> Stashed changes
  domain: ashwingowda.com
  liveSubDomainName: prod-demo-live
  previewSubDomainName: prod-demo-preview