apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: main
  namespace: argocd
spec:
  description: This project will be used to host charts from ashwinkmdevops helm repo for development of node-project
  sourceRepos:
    - https://ashwinkmdevops.github.io/helm-charts
    - https://github.com/akm-devops/node_project.git
  destinations:
    - namespace: 'main-app'
      name: 'in-cluster'
      server: https://kubernetes.default.svc  # Allow deployment to any cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
