fullName: 'demo'

replicaCount: 5

image:
  repository: ashwinkmgowda/nodejs-image-demo
  pullPolicy: IfNotPresent
  tag: "59"

controllerType: Rollout

liveService: 'demo-live'
previewService: 'demo-preview'
serviceType: ClusterIP

ports:
  http:
    port: 80

targetPort: 8080

# Chose only one type
rolloutStrategy:
  blueGreen:
    autoPromotionEnabled: true
    autoPromotionSeconds: 15

  # canary:
  #   steps:
  #   - setWeight: 20
  #   - pause:
  #       duration: 10s
  #   - setWeight: 40
  #   - pause:
  #       duration: 10s
  #   - setWeight: 60
  #   - pause:
  #       duration: 10s
  #   - setWeight: 80
  #   - pause:
  #       duration: 10s
  #   - setWeight: 100


connection: true
domain: localhost
liveDNSName: demo-live.localhost
previewDNSName: demo-preview.localhost