name: Branch Deploy

on:
  workflow_dispatch:
    # This workflow is triggered manually via the GitHub UI
    inputs:
      branch_name:
        description: 'Choose the target branch to deploy'
        required: true
        default: 'development'

jobs:
  deploy:
    name: Deploy Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched for branch checks
          # This is important to ensure that the branch exists in the remote repository
          
      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1
        with:
          version: v3.0.6 # optional 

      - name: ArgoCD Login
        run: |
          argocd login argocd.ashwingowda.com \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      - name: Get App Details
        run: |
          argocd app get node-project-development

      - name: Check if branch exists
        run: |
          if ! git ls-remote --heads origin ${{ github.event.inputs.branch_name }}; then
            echo "Branch ${{ github.event.inputs.branch_name }} does not exist."
            exit 1
          fi
          
      - name: Deploy to branch
        run: |
            argocd app set node-project-development \
              --source-position 2 \
              --grpc-web \
              --revision ${{ github.event.inputs.branch_name }}

      - name: ArgoCD Logout
        run: |
          argocd logout argocd.ashwingowda.com
          # Ensure to log out after the operations to clean up session