name: Branch Deploy

on:
  workflow_dispatch:
    # This workflow is triggered manually via the GitHub UI
    inputs:
      branch_name:
        description: 'Choose the target branch to deploy'
        required: true
        default: 'development'

jobs:
  deploy:
    name: Deploy Branch
    runs-on: ubuntu-latest
    steps:
      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1
        with:
          version: v3.0.6 # optional 

      - name: ArgoCD Login
        run: |
          argocd login argocd.ashwingowda.com --username admin --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: ArgoCD Logout
        run: |
          argocd logout argocd.ashwingowda.com
          # Ensure to log out after the operations to clean up session
      - name: Deploy to branch
        run: |
          which argocd
          argocd --help