name: Build with Buildah

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Choose the Runner'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - runner-scale-set-kubernetes
          - runner-scale-set-dind
          - ubuntu-latest

env:
  IMAGE_NAME: nodejs-image-demo
  IMAGE_REGISTRY: docker.io
  IMAGE_NAMESPACE: ashwinkmgowda

jobs:
  build:
    name: Build and push image
    runs-on: ${{ inputs.runner }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set Build Variables
      id: set-vars
      run: |
        # echo "image_tag=$(echo $GITHUB_SHA  | cut -c1-6)" >> $GITHUB_OUTPUT
        echo "image_tag_sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

    - name: Print SHA tag
      run: |
        echo "Image Tag SHA: ${{ steps.set-vars.outputs.image_tag_sha }}"

    - name: Determine base branch and sanitize
      id: determine-branch
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
        else
          BASE_BRANCH="${GITHUB_REF#refs/heads/}"
        fi

        # Sanitize branch name for Docker tag (replace slashes with dashes)
        SANITIZED_BRANCH=$(echo "$BASE_BRANCH" | sed 's#/#-#g')
        echo "image_tag_branch=${SANITIZED_BRANCH}-${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Print branch tag
      run: |
        echo "Image Tag Branch: ${{ steps.determine-branch.outputs.image_tag_branch }}"

    - name: Set Image Tags
      run: |
        echo "IMAGE_TAGS=latest ${{ steps.set-vars.outputs.image_tag_sha }} ${{ steps.determine-branch.outputs.image_tag_branch }}" >> $GITHUB_ENV

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        containerfiles: |
          ./Dockerfile

    - name: Push To Docker Hub
      id: push-to-dockerhub
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Print image URLs
      run: echo "Image pushed to ${{ steps.push-to-dockerhub.outputs.registry-paths }}"