# build-with-kaniko.yml

name: Build with kaniko
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        default: runner-scale-set-kubernetes

# env:
#   KANIKO_CACHE_ARGS: "--cache --cache-copy-layers --cache-ttl=24h"

jobs:

  build-to-dockerhub:
    runs-on:
      - ${{ inputs.arc_name }}
    container:
      image: gcr.io/kaniko-project/executor:v1.23.2-debug # the kaniko image
    permissions:
      contents: read # read the repository

    steps:
      - name: Build and Push Image to Dockerhub with kaniko
        run: |
          cat <<EOF > /kaniko/.docker/config.json
          { "auths": { "https://index.docker.io/v1/": { "auth": "${{ secrets.DOCKERHUB_AUTH }}" } } }
          EOF
          
          /kaniko/executor --dockerfile="./Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --destination=ashwinkmgowda/nodejs-image-demo:${{ github.run_number }}\
            --push-retry 5
