# build-with-kaniko.yml

name: Build with kaniko
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        default: runner-scale-set-kubernetes

# env:
#   KANIKO_CACHE_ARGS: "--cache --cache-copy-layers --cache-ttl=24h"

jobs:

  build-to-acr:
    runs-on:
      - ${{ inputs.arc_name }}
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug # the kaniko image
    permissions:
      contents: read # read the repository

    steps:
      - name: Build and Push Image to Dockerhub with kaniko
        run: |
          pwd
          ls -a
          cat <<EOF > /kaniko/.docker/config.json
          { "auths": { "https://index.docker.io/v1/": { "auth": "${{ secrets.DOCKERHUB_AUTH }}" } } }
          # { "credHelpers": { "${{ env.ACR_URL }}": "acr-env" } }
          EOF

          pwd
          ls -a
          
          /kaniko/executor --dockerfile="./Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --no-push \
            --push-retry 5
            
            # ${{ env.KANIKO_CACHE_ARGS }} \
            # --destination=ashwinkmgowda/nodejs-image-demo:$(date +%Y%m%d%H%M%S)
            
          # /kaniko/executor --dockerfile="./app/Dockerfile" \
          #   --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
          #   --destination="$ACR_URL/$NAMESPACE/nginx:$(echo ${GITHUB_SHA} | head  -c 7)" \
          #   ${{ env.KANIKO_CACHE_ARGS }} \
          #   --push-retry 5 
        # env:  # authenticate to ACR via Azure Service Principal
        #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        #   GIT_USERNAME: ${{ github.actor }}
        #   GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        #   ACR_URL: "myacr.azurecr.io"
        #   NAMESPACE: "frontend-apps"
