name: Build and Push Docker Image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `runs-on` in job'
        default: ubuntu-latest

jobs:
  build:
    runs-on:
      - ${{ inputs.arc_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_AUTH: ${{ secrets.DOCKERHUB_AUTH }}
      run: echo "${{ secrets.DOCKERHUB_AUTH }}" | docker login --username <your-username> --password-stdin

    - name: Build Docker image
      run: docker build . -t ashwinkmgowda/nodejs_image_demo:${{ github.run_number }}

    - name: Push Docker image to Docker Hub
      run: docker push ashwinkmgowda/nodejs_image_demo:${{ github.run_number }}
